env:
  global:
  - BIN_DIR=$HOME/bin
  - secure: YEL6nNH96OoaNlYxrfICOhi9kx6GNlSnBPsye0jNO/S253RcPhHDg0jEosAfiYQTivuqwxSIDtc1Ptq7YsB+s041lLBg75xpkOGCHM87wQhOczyTUNtS/Z5Tls7hO2WPxQ/Iw2njco2jMJdlyLG2HRJoRf9i5yW6NrPPER9KYf1QytrqXmpHbPljuuDsR8bb9DP1Inei2gO6ceZABtbqyWys+r1GGXvJmoj2R7Xsy2mJNX48bzHOPjzk4DJEqC2fXS7j2RquRlR2kbgPQ8x1mEOSGbC88gItpIv19jt2UD0IRzwWkfSW6wIwgKlSjaQHTRxaqkq2+ppN7RwotE+7dMpjK0Aw7EW18YaGOLtKzFECP9xPq5cIpl/7YjWqujYnWN/emh+Lp80YRCklqadFMxcJ4my/Cws2rujZ9fT3jsN+xPr//WsuIKsEJxSvk7+xYEtM86DKAciiV8OJI6rajJ/9w8K0kS3GJqSqLDRcWL4vxCXoGLm7U1Xu/abiwio/Ts4nwk97eqM/MFqTL/L+NZBrE0K7JsOWnatGAsxJ/i1zMXoi6zb3LYj6LQsc0x0IHUlCS2u8fDdF3Xw4VOHydeSQAnnrJ8yGKkPkqSuX752w8G987QxmkFUKRRHTn+7uoXkNrAdQrln+r6sdjdIP36ZhHlOwUqhTZYLHKZNexZ0=
  - secure: nV3dlkMc+uDQ/uLhsMD5WSClD3yICfNVBGV6L243jJ/1+BhXlQ8SjNUIhB+QkRc9PyXcy6PifWTra8OJT3n6a5AoJdiAnEcHSqsj6OsEs61yXsbjTDVY/fa8YTgJRQAZInFAdH/II7w51WkFy+Jb/MMUNwN+yO2U7tyhYUHcLaANQJwhfHjQMRZN37geufnBKq3jvM4Ssu/ufg1mfKHdNv/r/O/aZEp2T2u6+S7Jz01WwGusnHV3tDfI7r8F98j5+nsLFKn5xSnCgGeoaeV3jQZtuj6zIrwvyPffXW+tHjUsBCyHTJFbJpk1bUSckmxWLuFNxhP/B7pjJblq6YND/CkxdroVaSWXKkDWiioBWYTLtRTkazNczAh4t6S9DFucBWBNPC2sHFyJOjh9NOC7FE684axJNNmEZc/VVo+2g2TKoP46mo2c6tFt5rhHi9PE0ELgi3eqvx5YiiiQ+SAQNZAPaYfzdHSBDbL47Q31ZHhpPU9ZP8/Xj2XMN7Opk8rgw0ZPCqQeu27v3a50zljrxodhZdv/JqYISE+evBLdES2QEw0rW4pKLjOD1hzV4uIwIQ3ICTeRIkRCF8h46R9AKv7DU/NyKOeQfVUR9YJd1WVuSLPH6MyBoUDkpAuu0pcWYqfXxD7cuOox1Y9OPAZxPGXVcKIc05EhrUMF4y1/Mjs=
sudo: required
language: python
services:
- docker
script: 
post_install: 
before_deploy:
- wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip
- unzip /tmp/terraform.zip -d /tmp
- mkdir -p $BIN_DIR
- mv /tmp/terraform $BIN_DIR/
- export PATH=$PATH:$BIN_DIR
- rm -f /tmp/terraform.zip
deploy:
- cd terraform
- terraform init
- terraform taint 'aws_instance.front.0'
- terraform apply -auto-approve
- terraform taint 'aws_instance.front.1'
- terraform apply -auto-approve
- cd ..
before_install: 
